language: generic

#dotnet cli require Ubuntu 14.04
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - libicu52
    - dbus

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview2-003121

script:
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found"
      exit 1;
    fi
  # dotnet restore
  - dotnet restore
  # Build projects 
  - dotnet build ./src/NetCore
  - dotnet build ./src/NetCoreXunit
  # Build wildcard so it picks up NetCoreXunitB as well
  - dotnet build ./src/**/project.json
  
after_success:
  # Run tests
  - dotnet test ./src/NetCoreXunit -xml ./out/NetCoreXunit.xml;
    if grep -q 'result="Fail"' ./out/NetCoreXunit.xml ;  then
      echo 'Failed tests detected.';
    else
      echo 'All tests passed.';
    fi;
  - dotnet test ./src/NetCoreXunitB -xml ./out/NetCoreXunitB.xml;
    if grep -q 'result="Fail"' ./out/NetCoreXunitB.xml ;  then
      echo 'Failed tests detected.';
    else
      echo 'All tests passed.';
    fi;
  - dotnet test -help
  - Travis.py

  