language: csharp
solution: NetCoreXunit.sln

python:
  - "2.7"

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - libicu52
    - dbus

matrix:
  include:
    - os: osx
      osx_image: xcode7.1
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
	  
notifications:
  email:
    on_success: change
    on_failure: always

script:
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found"
      exit 1;
    fi
  # dotnet restore
  - dotnet restore
  # Build projects 
  - dotnet build ./src/NetCore
  - dotnet build ./src/NetCoreXunit
  # Build wildcard so it picks up NetCoreXunitB as well
  - dotnet build ./src/**/project.json
  # Run tests
  - python Travis.py